// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFdkiGoKRLQWwdCBmtYOV1a0weSzpk7MY',
    appId: '1:319397581807:web:9a463389312dc9ab6d1c1a',
    messagingSenderId: '319397581807',
    projectId: 'online-todo-5e4a2',
    authDomain: 'online-todo-5e4a2.firebaseapp.com',
    storageBucket: 'online-todo-5e4a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6bHTRTbYex6_1YgkRW-JtmtX87WrP84A',
    appId: '1:319397581807:android:d4dce43eb583c0a66d1c1a',
    messagingSenderId: '319397581807',
    projectId: 'online-todo-5e4a2',
    storageBucket: 'online-todo-5e4a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHUZNFIBue_oabJxbekspKTybSfD0QcW4',
    appId: '1:319397581807:ios:67a3d0ede1cb08e66d1c1a',
    messagingSenderId: '319397581807',
    projectId: 'online-todo-5e4a2',
    storageBucket: 'online-todo-5e4a2.firebasestorage.app',
    iosBundleId: 'com.example.providerLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHUZNFIBue_oabJxbekspKTybSfD0QcW4',
    appId: '1:319397581807:ios:67a3d0ede1cb08e66d1c1a',
    messagingSenderId: '319397581807',
    projectId: 'online-todo-5e4a2',
    storageBucket: 'online-todo-5e4a2.firebasestorage.app',
    iosBundleId: 'com.example.providerLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFdkiGoKRLQWwdCBmtYOV1a0weSzpk7MY',
    appId: '1:319397581807:web:0113ca0c2d04b4046d1c1a',
    messagingSenderId: '319397581807',
    projectId: 'online-todo-5e4a2',
    authDomain: 'online-todo-5e4a2.firebaseapp.com',
    storageBucket: 'online-todo-5e4a2.firebasestorage.app',
  );
}
